package com.agentrunner.workflow;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.nio.file.StandardOpenOption;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

@Component
class McpConfigWriter {

    private final ObjectMapper objectMapper;

    McpConfigWriter(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }

    void writeClaudeMcpConfig(Path projectRoot, ObjectNode mergedConfig) {
        Path claudeConfig = projectRoot.resolve(".mcp.json");
        try {
            String json = objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(mergedConfig);
            Files.writeString(
                    claudeConfig,
                    json + System.lineSeparator(),
                    StandardCharsets.UTF_8,
                    StandardOpenOption.CREATE,
                    StandardOpenOption.TRUNCATE_EXISTING
            );
        } catch (IOException e) {
            throw new IllegalStateException("failed to write Claude MCP config: " + claudeConfig, e);
        }
    }

    void writeCopilotMcpConfig(Path projectRoot, ObjectNode mergedConfig) {
        Path vscodeDir = projectRoot.resolve(".vscode");
        Path copilotConfig = vscodeDir.resolve("mcp.json");
        try {
            Files.createDirectories(vscodeDir);
            ObjectNode copilotFormat = toCopilotFormat(mergedConfig);
            String json = objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(copilotFormat);
            Files.writeString(
                    copilotConfig,
                    json + System.lineSeparator(),
                    StandardCharsets.UTF_8,
                    StandardOpenOption.CREATE,
                    StandardOpenOption.TRUNCATE_EXISTING
            );
        } catch (IOException e) {
            throw new IllegalStateException("failed to write Copilot MCP config: " + copilotConfig, e);
        }
    }

    private ObjectNode toCopilotFormat(ObjectNode mergedConfig) {
        ObjectNode result = objectMapper.createObjectNode();
        JsonNode servers = mergedConfig.path("mcpServers");
        if (!servers.isObject()) {
            result.set("servers", objectMapper.createObjectNode());
            return result;
        }
        ObjectNode copilotServers = objectMapper.createObjectNode();
        servers.fields().forEachRemaining(entry -> {
            JsonNode original = entry.getValue();
            ObjectNode copy = original.deepCopy().isObject()
                    ? (ObjectNode) original.deepCopy()
                    : objectMapper.createObjectNode();
            if (!copy.has("type")) {
                copy.put("type", "stdio");
            }
            copilotServers.set(entry.getKey(), copy);
        });
        result.set("servers", copilotServers);
        return result;
    }

    void writeGeminiMcpConfig(Path projectRoot, ObjectNode mergedConfig) {
        Path geminiDir = projectRoot.resolve(".gemini");
        Path geminiConfig = geminiDir.resolve("settings.json");
        try {
            Files.createDirectories(geminiDir);
            String json = objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(mergedConfig);
            Files.writeString(
                    geminiConfig,
                    json + System.lineSeparator(),
                    StandardCharsets.UTF_8,
                    StandardOpenOption.CREATE,
                    StandardOpenOption.TRUNCATE_EXISTING
            );
        } catch (IOException e) {
            throw new IllegalStateException("failed to write Gemini MCP config: " + geminiConfig, e);
        }
    }

    Path writeCodexMcpServersToml(Path projectRoot, JsonNode serversNode) {
        Path codexConfig = projectRoot.resolve("mcp-servers.toml");

        StringBuilder sb = new StringBuilder();
        sb.append("# Codex CLI MCP Server Configuration").append(System.lineSeparator());
        sb.append("# Generated by Agent Runner").append(System.lineSeparator());
        sb.append("# Source profiles: skills/agent-runner-mcp-setup/profiles + defaults").append(System.lineSeparator());

        serversNode.fields().forEachRemaining(entry -> {
            String serverName = entry.getKey();
            JsonNode serverConfig = entry.getValue();
            String type = serverConfig.path("type").asText("stdio").toLowerCase(Locale.ROOT);

            sb.append(System.lineSeparator())
                    .append("[mcp_servers.")
                    .append(quoteTomlKey(serverName))
                    .append("]")
                    .append(System.lineSeparator());

            if ("http".equals(type)) {
                String url = serverConfig.path("url").asText("");
                if (url.isBlank()) {
                    throw new IllegalStateException("HTTP MCP server requires url: " + serverName);
                }
                sb.append("url = \"").append(escapeTomlString(url)).append("\"").append(System.lineSeparator());
                String bearerTokenEnvVar = serverConfig.path("bearer_token_env_var").asText("");
                if (!bearerTokenEnvVar.isBlank()) {
                    sb.append("bearer_token_env_var = \"")
                            .append(escapeTomlString(bearerTokenEnvVar))
                            .append("\"")
                            .append(System.lineSeparator());
                }
                return;
            }

            String command = serverConfig.path("command").asText("");
            if (command.isBlank()) {
                throw new IllegalStateException("STDIO MCP server requires command: " + serverName);
            }

            sb.append("command = \"").append(escapeTomlString(command)).append("\"").append(System.lineSeparator());
            sb.append("args = ").append(toTomlArray(extractStringList(serverConfig.path("args")))).append(System.lineSeparator());

            Map<String, String> env = extractEnvMap(serverConfig.path("env"));
            if (!env.isEmpty()) {
                sb.append("[mcp_servers.")
                        .append(quoteTomlKey(serverName))
                        .append(".env]")
                        .append(System.lineSeparator());
                env.forEach((key, value) -> sb.append(quoteTomlKey(key))
                        .append(" = \"")
                        .append(escapeTomlString(value))
                        .append("\"")
                        .append(System.lineSeparator()));
            }
        });

        try {
            Files.writeString(
                    codexConfig,
                    sb.toString(),
                    StandardCharsets.UTF_8,
                    StandardOpenOption.CREATE,
                    StandardOpenOption.TRUNCATE_EXISTING
            );
        } catch (IOException e) {
            throw new IllegalStateException("failed to write Codex MCP server template: " + codexConfig, e);
        }

        return codexConfig;
    }

    void linkProjectCodexConfig(Path projectRoot, Path mcpServersToml) {
        Path codexDir = projectRoot.resolve(".codex");
        Path projectCodexConfig = codexDir.resolve("config.toml");

        try {
            Files.createDirectories(codexDir);
            Files.deleteIfExists(projectCodexConfig);
            try {
                Files.createSymbolicLink(projectCodexConfig, mcpServersToml);
            } catch (UnsupportedOperationException | IOException ignored) {
                Files.copy(mcpServersToml, projectCodexConfig, StandardCopyOption.REPLACE_EXISTING);
            }
        } catch (IOException e) {
            throw new IllegalStateException("failed to link project codex config: " + projectCodexConfig, e);
        }
    }

    static List<String> extractStringList(JsonNode node) {
        if (node == null || !node.isArray()) {
            return List.of();
        }
        List<String> values = new ArrayList<>();
        node.forEach(item -> {
            if (item.isTextual()) {
                values.add(item.asText());
            }
        });
        return values;
    }

    static Map<String, String> extractEnvMap(JsonNode node) {
        if (node == null || !node.isObject()) {
            return Map.of();
        }
        Set<String> keys = new LinkedHashSet<>();
        node.fieldNames().forEachRemaining(keys::add);
        LinkedHashMap<String, String> env = new LinkedHashMap<>();
        for (String key : keys) {
            env.put(key, node.path(key).asText(""));
        }
        return env;
    }

    static String quoteTomlKey(String value) {
        return "\"" + escapeTomlString(value) + "\"";
    }

    static String escapeTomlString(String value) {
        return value
                .replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\n", "\\n")
                .replace("\r", "\\r")
                .replace("\t", "\\t");
    }

    static String toTomlArray(List<String> values) {
        if (values == null || values.isEmpty()) {
            return "[]";
        }
        List<String> escaped = new ArrayList<>(values.size());
        for (String value : values) {
            escaped.add("\"" + escapeTomlString(value) + "\"");
        }
        return "[" + String.join(", ", escaped) + "]";
    }
}
